import type { Metadata } from "next";
import "@/styles/globals.css";
import Navbar from "@/components/navbar/navbar";
import { Footer } from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "Cyber Reports",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <section className="relative">
          {children}
        </section>
        <Footer />
      </body>
    </html>
  );
}
